### ISSUE TITLE
sql 中的日志解析功能，解析sql日志类型为「通用sql日志解析」，其中参数为 null 可以一个特殊字符串，不应当被 '' 包裹

### ISSUE THREAD

**Issue by springandme** [mzlxl/sql-tool#1]
![image](https://github.com/mzlxl/sql-tool/assets/44739137/366a1a24-a6b1-48c8-a507-a38c942ff7e9)

**Comment by mzlxl** [comment]
抱歉没有关注到issue，已经优化提审批，明天就可以使用
